version: "3.9"

services:
  pokerth-server:
    image: baptistecdr/pokerth-server:1.1.2-0
    container_name: pokerth-server
    ports:
      - "7234:7234"
    volumes:
      - ./config.xml:/pokerth/.pokerth/config.xml
