version: "3.9"

services:
  pokerth-server:
    image: baptistecdr/pokerth-server:1.1.2-0@sha256:e1ef2400e59fce2fc2ec3c870e0f33c5c469762ddd3adaf0027e4784f8041ceb
    container_name: pokerth-server
    ports:
      - "7234:7234"
    volumes:
      - ./config.xml:/pokerth/.pokerth/config.xml
